export const STORE_WORKOUT_DATA = 'ADD_TO_CART';
export const CALCULATE_BEST_POWER_PERIODS = 'CALCULATE_BEST_POWER_PERIODS';
export const BUILD_ROUTE_DATA = 'BUILD_ROUTE_DATA';

export const HIGHLIGHT_ROUTE= 'HIGHLIGHT_ROUTE';
export const CLEAR_HIGHLIGHT_ROUTE = 'CLEAR_HIGHLIGHT_ROUTE';

export const SET_SELECTOR_OPTION = 'SET_SELECTOR_OPTION';

export const SET_LOADING_STATE = 'SET_LOADING_STATE';

export const ENTIRE_MINUTES = "ENTIRE";
export const CUSTOM_MINUTES = "CUSTOM";
export const BEST_1_MINUTES = "1";
export const BEST_5_MINUTES = "5";
export const BEST_10_MINUTES = "10";
export const BEST_15_MINUTES = "15";
export const BEST_20_MINUTES = "20";

export const SET_SEGMENT_AVERAGE_POWER = "SET_SEGMENT_AVERAGE_POWER";